import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  bgImg: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  darker: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0,0,0,0.4)",
    zIndex: 10,
  },
  tree: {
    height: "75%",
    width: "35%",
    borderRadius: 10,
  },
  player: {
    width: "25%",
    height: "20%",
    bottom: "20%",
    right: "10%",
    position: "absolute",
  },
  content: {
    width: "100%",
    height: "100%",
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-start",
    flexDirection: "row",
    position: "relative",
    opacity: 0.85,
  },
  txt: {
    fontSize: 40,
    color: "#fff",
    paddingBottom: 20,
  },
  txtCont: {
    width: "100%",
    height: "100%",
    position: "absolute",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  name: {
    fontSize: 60,
    color: "#fff",
    top: "-20%",
    zIndex: 20,
    opacity: 1,
    textAlign: "center",
  },
  log: {
    width: 100,
    height: 50,
    position: "absolute",
    left: 150,
    top: 150,
  },
});
